---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 20Gi

  storageClassName: local-hostpath
