---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cnpg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_R2_ENDPOINT: "https://{{ .cloudflare_account_id }}.r2.cloudflarestorage.com"
  data:
    - secretKey: cloudflare_account_id
      remoteRef:
        key: cloudflare
        property: account_id
