---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    tailscale.com/hostname: "rook"
  namespace: rook-ceph
spec:
  defaultBackend:
    service:
      name: rook-ceph-mgr-dashboard
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - rook
