---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-peertube
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/apps/peertube/peertube/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-crunchy-postgres-operator
    - name: cluster-apps-redis-peertube
---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-redis-peertube
  namespace: flux-system
spec:
  path: ./kubernetes/apps/peertube/peertube/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
