---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: statsd-exporter
  namespace: fediverse
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    command: ["/bin/sh", "-c", "statsd_exporter --statsd.mapping-config=/config/mastodon-mapping.yaml"]
    image:
      repository: docker.io/prom/statsd-exporter
      tag: v0.24.0@sha256:61d866e93b56c7d5c69ae5ba5ce4f8a16a98f4b13985ad3385bd8e0b2371126e

    service:
      main:
        ports:
          http:
            port: 9125
            enabled: true
            primary: true
            protocol: TCP
          api:
            enabled: true
            port: 9102

    persistence:
      config:
        enabled: true
        type: configMap
        name: statsd-configmap
        subPath: mastodon-mapping.yaml
        mountPath: /config/mastodon-mapping.yaml
        readOnly: true

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 46m
        memory: 270M
