---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fediverse
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: statsd-configmap
    files:
      - mappings/mastodon-mapping.yaml
generatorOptions:
  disableNameSuffixHash: true
