on: [push]
  workflow_call:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
        type: string
      renovateLogLevel:
        description: "Log-Level"
        default: "debug"
        required: false
        type: string
      configurationFile:
        description: "Renovate configuration file"
        default: ".github/renovate.json5"
        required: false
        type: string
    secrets:
      app_id:
        description: "App ID of the application used to generate a token"
        required: true
      app_private_key:
        description: "Private key of the application used to generate a token"
        required: true

jobs:
  renovate:
    name: Renovate
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.token }}'

      - name: Renovate
        uses: renovatebot/github-action@v39.0.1
        env:
          DRY_RUN: ${{ inputs.dryRun }}
          LOG_LEVEL: ${{ inputs.renovateLogLevel }}
        with:
          configurationFile: ${{ inputs.configurationFile }}
          token: '${{ secrets.token }}'