on: [push]
jobs:
  renovate-dry:
    runs-on: docker
    services:
      renovate:
        image: ghcr.io/renovatebot/renovate:36.52.2
        env:
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: https://git.hsn.dev
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
        # cmd:
        #   - 'renovate'
        #   - jahanson/valinor
    steps:
      - run: |
          renovate jahanson/valinor
