platform: linux/amd64

when:
  event:
    - cron
    - push
    - manual

pipeline:
  renovate-dry:
    image: ghcr.io/renovatebot/renovate:36.52.2
    pull: true
    commands:
      - renovate $${CI_REPO} jahanson/valinor
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.hsn.dev
      LOG_LEVEL: debug
      RENOVATE_DRY_RUN: full
    secrets:
      - source: token
        target: renovate_token
    when:
      - event: push
  renovate:
    image: ghcr.io/visualon/renovate:36.52.2
    pull: true
    commands:
      - renovate $${CI_REPO} jahanson/valinor
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.hsn.dev
      LOG_LEVEL: debug
    secrets:
      - source: token
        target: renovate_token
    when:
      - event: cron
        cron: renovate
      - event: manual
