---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fediverse
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # - ./ingress.yaml
  - ./postgresCluster.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: peertube-configmap
    files:
      - config/production.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
