---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peertube-config
  namespace: fediverse
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
