---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-crowdsec
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 30m
  path: "./kubernetes/apps/security/crowdsec/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
