# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-elk
#   namespace: flux-system
#   labels:
#     substitution.flux.home.arpa/enabled: "true"
# spec:
#   interval: 10m
#   path: "./kubernetes/valinor/apps/fediverse/elk/app"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: valinor
#   wait: true
#   dependsOn:
#     - name: cluster-apps-external-secrets-stores
