---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hcloud
    creationPolicy: Owner
  data:
    - secretKey: network
      remoteRef:
        key: hetzner
        property: cloud-api-token
