---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hccm
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: v1.18.0
      sourceRef:
        kind: HelmRepository
        name: hetzner
        namespace: flux-system
      interval: 30m
  values:
    image:
      repository: ghcr.io/jahanson/hccm
      tag: v1.19.1
    env:
      ROBOT_USER:
        valueFrom:
          secretKeyRef:
            name: hcloud
            key: robot-user
            optional: true
      ROBOT_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: hcloud
            key: robot-password
            optional: true
      HCLOUD_TOKEN:
        valueFrom:
          secretKeyRef:
            name: hcloud
            key: token
            optional: true
    metrics:
      enabled: true
    networking:
      enabled: false
    robot:
      enabled: true
