apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-apps-elastic-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/valinor/apps/elastic/operator/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: valinor
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: eck-operator
      namespace: elastic
  interval: 30m
  retryInterval: 1m
  timeout: 3m
