---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: main@sha256:9346cb845868c70d37c89f7d0ff66debb3bce166410ff5251281cf03a8c54d84
              pullPolicy: IfNotPresent
    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      main:
        ports:
          http:
            port: 9093

    ingress:
      main:
        classname: nginx
        hosts:
          - host: &host alertmanager.hsn.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: alertmanager-configmap
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        enabled: true
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/secrets

    resources:
      requests:
        cpu: 11m
        memory: 50M
      limits:
        memory: 99M

    volumeClaimTemplates:
      - name: storage
        mountPath: /alertmanager
        accessMode: ReadWriteOnce
        size: 50Mi
