apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: disk-wipe
      image: ghcr.io/onedr0p/alpine:3.17.3@sha256:999384960b6114496a5e4036e945141c205d064ce23b87326bd3f8d878c5a9d4
      securityContext:
        privileged: true
      resources: {}
      command: ["/bin/sh", "-c"]
      args:
        - apk add --no-cache sgdisk util-linux parted e2fsprogs;
          sgdisk --zap-all /dev/nvme1n1;
          blkdiscard /dev/nvme1n1;
          dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/nvme1n1;
          sgdisk /dev/nvme1n1
          partprobe /dev/nvme1n1;
