---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./externalsecret.yaml
  - ./postgresCluster.yaml

commonLabels:
  app.kubernetes.io/name: authentik
  app.kubernetes.io/instance: authentik
