---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flow-schema-reader
rules:
  - apiGroups: ["flowcontrol.apiserver.k8s.io"]
    resources: ["flowschemas", "prioritylevelconfigurations"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grant-flow-schema-permission
subjects:
  - kind: ServiceAccount
    name: dnsimple-issuer-cert-manager-webhook-dnsimple
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: flow-schema-reader
  apiGroup: rbac.authorization.k8s.io
