---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ./externalsecret.yaml
  - ./issuer-letsencrypt-prod.yaml
  - ./issuer-letsencrypt-staging.yaml
  - ./dnsimple-issuer-rbac.yaml
  - ./helmrelease.yaml
