apiVersion: v1
kind: Pod
metadata:
  name: rocky-nessa
  namespace: default
spec:
  nodeName: nessa
  containers:
    - name: rocky
      image: rockylinux:9
      securityContext:
        privileged: true
      command: ["/bin/bash", "-c", "while true; do sleep 10; done"]
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 4000m
          memory: 4000Mi
