---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: peertube-server
  namespace: peertube
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/chocobozzz/peertube
              tag: &peertube-version v6.0.2-bookworm
            command:
              - "/bin/sh"
              - "-c"
            args:
              - cp /app/support/docker/production/config/* /config;
                cp /app/config/default.yaml /config;
                chown -R peertube:peertube /data /config;
                cp -r /app/client/dist/* /assets/;
        containers:
          main:
            image:
              repository: docker.io/chocobozzz/peertube
              tag: *peertube-version
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: peertube-secret
            probes:
              readinessProbe:
                httpGet:
                  path: /api/v1/instance
                  port: 9000
                initialDelaySeconds: 15
              livenessProbe:
                httpGet:
                  path: /api/v1/instance
                  port: 9000
                failureThreshold: 3
                periodSeconds: 30
                initialDelaySeconds: 15
          nginx:
            image:
              repository: docker.io/library/nginx
              tag: 1.25.3-alpine
              pullPolicy: Always
    service:
      main:
        ports:
          http:
            port: &port-api 9000

    persistence:
      # config:
      #   enabled: true
      #   type: configMap
      #   name: peertube-configmap
      #   globalMounts:
      #     - path: /config
      nginx-conf:
        enabled: true
        type: configMap
        name: peertube-nginx
        globalMounts:
          - path: /etc/nginx/conf.d
      assets:
        type: emptyDir
        globalMounts:
          - path: /assets


    resources:
      requests:
        cpu: 4000m
        memory: 500Mi
      limits:
        cpu: 4000m
