---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peertube-config
  namespace: peertube
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 200Mi
  storageClassName: ceph-filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peertube-media
  namespace: peertube
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Ti
  storageClassName: ceph-filesystem
