---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: erebor
  namespace: fediverse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: erebor-scrape-creds
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: erebor_scrape_bearer_token
        property: minio
