---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-peertube
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 30m
  values:
    controller:
      replicaCount: 3
      updateStrategy:
        type: RollingUpdate
      allowSnippetAnnotations: true
      enableAnnotationValidations: true
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          load-balancer.hetzner.cloud/location: fsn1
          load-balancer.hetzner.cloud/protocol: tcp
          load-balancer.hetzner.cloud/name: peertube-nginx
          load-balancer.hetzner.cloud/use-private-ip: true
          load-balancer.hetzner.cloud/uses-proxyprotocol: true

      publishService:
        enabled: true

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: network
          namespaceSelector:
            any: true

      ingressClassResource:
        name: peertube-nginx
        default: false

      config:
        block-user-agents: "GPTBot,~*GPTBot*,ChatGPT-User,~*ChatGPT-User*,Google-Extended,~*Google-Extended*,CCBot,~*CCBot*,Omgilibot,~*Omgilibot*,FacebookBot,~*FacebookBot*" # taken from https://github.com/superseriousbusiness/gotosocial/blob/main/internal/web/robots.go
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        enable-brotli: "true"
        enable-ocsp: "true"
        enable-real-ip: "true"
        use-proxy-protocol: "true"
        hide-headers: Server,X-Powered-By
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: 0
        proxy-buffer-size: "16k"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
        server-snippet: |
          resolver local=on ipv6=off;
          ssl_stapling on;
          ssl_stapling_verify on;
        ssl-echd-curve: "secp384r1"
        ssl-session-timeout: "1d"
        ssl-session-cache: "shared:SSL:10m"
        ssl-session-tickets: "off"

      extraArgs:
        default-ssl-certificate: "network/khazadtube-tv-tls"

      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: ingress-nginx-peertube
              app.kubernetes.io/component: controller
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - controller
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - ingress-nginx-peertube
              topologyKey: kubernetes.io/hostname

      resources:
        requests:
          cpu: 23m
          memory: 381M

    defaultBackend:
      enabled: false
