apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUSHOVER_USERKEY: ENC[AES256_GCM,data:MeaD8iRbieNr5W9PqpjZ5ywdbMijX9nYQJbbVj6s,iv:42QymFlr47PYNjorJc5tgDjzZ9WHPVIk543GGChalVM=,tag:qyk1chI/IpPdfyEMdOqsbQ==,type:str]
    SECRET_PUSHOVER_ALERT_MANAGER_APIKEY: ENC[AES256_GCM,data:4+9e/tWQBszoPakAo+1vNhWsdKz8qfoioeUz+dTb,iv:sY4dkzMEmvi8kCLesBiknmoYHWq3uqXpWs5Y4FeFSuk=,tag:rPxH+5m6rPiSnhm2JrrT4w==,type:str]
    SECRET_HEALTHCHECKS_WEBHOOK: ENC[AES256_GCM,data:+o+RcVsRsnnA1u5lvWOzsNdpjO0C7h2ixmgF1BZmVyl6HOeZfKVunHdAvNXMVKCxVw4z8d2AWSvxYbbyGYKkT/KsG2nD8lfJ,iv:sX79yidO42r+VTHXn7559+THI/KVRH1sl74DSfPnugY=,tag:KMqrGr9sbfdILOJS5RBUgg==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:X63a7aMBMyd9Be6bik0knOyMXnYx/Kg3SoOrG0bkAHU=,iv:POcU1kIRWekrzUdzqPopKDovviK+fMZRVuZVWp9Vuuc=,tag:n9UamxITJCiLbH37Ta2lTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g786w8t40g9y29l33rfd4jqlwhrgsxsc7ped6uju60k54j0q3enql3kfve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNUJOSGgzempjQS9ZQVlo
            citDR1Vta2ZHWHJYNElySzA4a1ZIdktQREhFCnZyQlYvYlhRbDlwYVkxZmZJYm5S
            TEU0c2R4WkFWZGNEcjYyTHE3MmVLT0kKLS0tIHZwQWNGYks1alNnYVAyOWZsL1J2
            dDhWMDZYait3UzNRZy9oVk85cHBPdEUKa7e22jHlW1chaLDKBB1in8ZTFnfKMXug
            QJQ/9z6z/RjmnnFam2FWg++Xg2A8LQ7XTZcfR97csf59DQ/xwu7sVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-14T05:22:27Z"
    mac: ENC[AES256_GCM,data:W5In3D9gjAeSNvNiUmcUsrUKnRmtppaVpo1IvenaPin2RpTRhql2vDQf4Eh6S85mPwOgLbS3E8gPzkaq7t6tXCVY5ELW5tQW0BXkuF0aICYfwaORUJgYSiNQ+E2v1uJlGfhnv6FsRo9TEGk+bswzRJgiupD38anS6qRy2CrmWyw=,iv:sdHy2KrnWLiLkHHWhyzRQ8E/gVAW7l6WDXdbA4Wd/ME=,tag:0rIcGmFCKL412iqMVXXFuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
