---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elk
  namespace: fediverse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: elk-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NUXT_CLOUDFLARE_API_TOKEN: "{{ .cloudflare_kv_storage_apikey }}"
        NUXT_CLOUDFLARE_ACCOUNT_ID: "{{ .cloudflare_account_id }}"
        NUXT_CLOUDFLARE_NAMESPACE_ID: "{{ .cloudflare_kv_storage_namespace }}"
        NUXT_STORAGE_DRIVER: "cloudflare"
  data:
    - secretKey: cloudflare_kv_storage_apikey
      remoteRef:
        key: cloudflare
        property: elk_kv_storage_apikey
    - secretKey: cloudflare_account_id
      remoteRef:
        key: cloudflare
        property: account_id
    - secretKey: cloudflare_kv_storage_namespace
      remoteRef:
        key: cloudflare
        property: elk_kv_storage_namespace
