---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/cert-manager/cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/cert-manager/cert-manager/issuers"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager
