---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/valinor/apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-external-secrets-stores
