---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-jump-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TS_AUTHKEY: "{{ .TS_AUTHKEY }}"
  dataFrom:
    - extract:
        key: tailscale-jump
