---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/security/external-secrets/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-stores
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/security/external-secrets/stores"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets
