apiVersion: v1
kind: Pod
metadata:
  name: rocky-linux
  namespace: default
spec:
  containers:
    - name: rocky
      image: rockylinux:9
      command: ["/bin/bash", "-c", "while true; do sleep 10; done"]
      resources:
        requests:
          cpu: 50m
          memory: 443M
        limits:
          cpu: 323m
          memory: 886M
