---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-redis-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/redis-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
