---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring.coreos.com_alertmanagers.yaml
  - ./monitoring.coreos.com_podmonitors.yaml
  - ./monitoring.coreos.com_prometheusrules.yaml
  - ./monitoring.coreos.com_servicemonitors.yaml
  - ./monitoring.coreos.com_thanosrulers.yaml
