---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dnsimple-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dnsimple-api-token
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: DNSimple
        property: cert-manager
    - secretKey: letsencrypt-email
      remoteRef:
        key: DNSimple
        property: letsencrypt-email
