---
# yaml-language-server: $schema=https://ks.hsn.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dnsimple-production
spec:
  acme:
    email: "joe@veri.dev"
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-dnsimple-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          webhook:
            config:
              tokenSecretRef:
                key: api-token
                name: dnsimple-api-token
            solverName: dnsimple
            groupName: acme.jahanson.com
