---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname snapshot-controller
  namespace: flux-system
spec:
  targetNamespace: system-controllers
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/main/apps/system/snapshot-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
  timeout: 2m
  dependsOn:
    - name: cluster-apps-cert-manager
